# Generated by Django 4.0.5 on 2022-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.IntegerField(null=True),
        ),
    ]
