# Generated by Django 4.0.5 on 2022-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.IntegerField(default=1656059199),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.IntegerField(default=1656059199),
        ),
    ]
